### ISSUE TITLE
Waste Management (arduino)

### ISSUE THREAD

**Issue by chicco785** [orchestracities/lego-diorama-usi-2022#6]
- collect data from sensors
- send data to ttn

(see old code)

**Comment by inchesg** [comment]
IR distance sensors measurements difficult to be interpreted and requires further investigation - today.

**Comment by casarf** [comment]
> IR distance sensors measurements difficult to be interpreted and requires further investigation - today.

We confused which sensor was to be used.  The sensor we have to use, the Groove Ultrasonic Ranger has been tested and works properly.
Anyway, it is still not possible to interpret the values given by the Infrared Proximity Sensor (with Arduino).

Sending data to TTN works properly, therefore the task can be considered closed.
