### ISSUE TITLE
TrafficCounter (raspberrypi)

### ISSUE THREAD

**Issue by chicco785** [orchestracities/lego-diorama-usi-2022#8]
- read ir sensor movement
- send reading to mqtt topic (1 topic per sensor / topic should be configurable for each sensor)

**Comment by Solargi** [comment]
issues:
missing obstacle detection sensor
the ir proximity sensor doesn't seem to work correctly

**Comment by inchesg** [comment]
exploration on how the ir sensor will work until the end of today with the help of Francesco
