### ISSUE TITLE
Turn on streetlight (raspberrypi)

### ISSUE THREAD

**Issue by chicco785** [orchestracities/lego-diorama-usi-2022#9]
- monitor mqtt queue (1 topic for streetlight or for street)
- if message received "turn on light" turn on light
- when command succesfully applied send message "light on" in the topic (same as above)

**Comment by Solargi** [comment]
Done the street_lights_client is configured with the config.ini file. when the message "turn on light" is received on the corresponding topic wither the lights of street 1 or 2 will be turned on for 5 seconds, the client will also publish the message "light on" on the topic that sent the first message. (the files are in the traffic directory)

tested the led module by connecting the actual streetlights and it works

**Comment by chicco785** [comment]
> tested the led module by connecting the actual streetlights and it works

the lego ones?

**Comment by Solargi** [comment]
yes

**Comment by inchesg** [comment]
to verify MQTT format see milestone #18 and #19, this task can be considered closed @chicco785
